/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:a79e19ae138ba1803e52a6aaebe89971:f133256da6590eed23d66328c3de2b59:c7cf1cde85eeac94c828f9f9f93e26ad$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class CharacterTextures
	{
		public const string Alert_0 = "alert_0";
		public const string Alert_1 = "alert_1";
		public const string Alert_2 = "alert_2";
		public const string Alert_3 = "alert_3";
		public const string Alert_4 = "alert_4";
		public const string Fly_0 = "fly_0";
		public const string Fly_1 = "fly_1";
		public const string Heal_0 = "heal_0";
		public const string Heal_1 = "heal_1";
		public const string Heal_2 = "heal_2";
		public const string Jump_0 = "jump_0";
		public const string Ladder_0 = "ladder_0";
		public const string Ladder_1 = "ladder_1";
		public const string ProneStab_0 = "proneStab_0";
		public const string ProneStab_1 = "proneStab_1";
		public const string Prone_0 = "prone_0";
		public const string Rope_0 = "rope_0";
		public const string Rope_1 = "rope_1";
		public const string Sit_0 = "sit_0";
		public const string StabO1_0 = "stabO1_0";
		public const string StabO1_1 = "stabO1_1";
		public const string StabO2_0 = "stabO2_0";
		public const string StabO2_1 = "stabO2_1";
		public const string StabOF_0 = "stabOF_0";
		public const string StabOF_1 = "stabOF_1";
		public const string StabOF_2 = "stabOF_2";
		public const string Stand1_0 = "stand1_0";
		public const string Stand1_1 = "stand1_1";
		public const string Stand1_2 = "stand1_2";
		public const string Stand1_3 = "stand1_3";
		public const string Stand1_4 = "stand1_4";
		public const string SwingO1_0 = "swingO1_0";
		public const string SwingO1_1 = "swingO1_1";
		public const string SwingO1_2 = "swingO1_2";
		public const string SwingO2_0 = "swingO2_0";
		public const string SwingO2_1 = "swingO2_1";
		public const string SwingO2_2 = "swingO2_2";
		public const string SwingO3_0 = "swingO3_0";
		public const string SwingO3_1 = "swingO3_1";
		public const string SwingO3_2 = "swingO3_2";
		public const string SwingOF_0 = "swingOF_0";
		public const string SwingOF_1 = "swingOF_1";
		public const string SwingOF_2 = "swingOF_2";
		public const string SwingOF_3 = "swingOF_3";
		public const string Walk1_0 = "walk1_0";
		public const string Walk1_1 = "walk1_1";
		public const string Walk1_2 = "walk1_2";
		public const string Walk1_3 = "walk1_3";
	}
}